/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/enterprises/{enterpriseId}/applications/{packageName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * アプリケーション情報の取得
         * @description 指定されたパッケージ名のアプリケーション情報を取得します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description エンタープライズID
                     * @example LC0283n6ru
                     */
                    enterpriseId: string;
                    /**
                     * @description アプリケーションのパッケージ名
                     * @example com.android.chrome
                     */
                    packageName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Application"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Application: {
            /**
             * @description アプリの名前（enterprises/{enterprise}/applications/{packageName} の形式）
             * @example enterprises/LC0283n6ru/applications/com.android.chrome
             */
            name?: string;
            /**
             * @description アプリのタイトル（ローカライズ済 ※地域に最適化されたもの）
             * @example Google Chrome
             */
            title?: string;
            /** @description アプリに必要な権限 */
            permissions?: components["schemas"]["ApplicationPermission"][];
            /** @description アプリ用に事前構成できる管理対象プロパティのセット */
            managedProperties?: components["schemas"]["ManagedProperty"][];
            /**
             * Format: uri
             * @description アプリのアイコン画像URL（最大512x512ピクセル）
             * @example https://example.com/icon.png
             */
            iconUrl?: string;
            /**
             * Format: uri
             * @description アプリの小さいアイコン画像URL（最大128x128ピクセル）
             * @example https://example.com/small_icon.png
             */
            smallIconUrl?: string;
            /** @description 企業に表示されるアプリケーショントラック */
            appTracks?: components["schemas"]["AppTrackInfo"][];
            /**
             * @description アプリの作成者名
             * @example Google LLC
             */
            author?: string;
            /**
             * Format: uri
             * @description Google Playストアの詳細ページURL
             * @example https://play.google.com/store/apps/details?id=com.android.chrome
             */
            playStoreUrl?: string;
            distributionChannel?: components["schemas"]["DistributionChannel"];
            appPricing?: components["schemas"]["AppPricing"];
            /**
             * @description ローカライズされたプロモーションの説明
             * @example Google Chromeは、高速で安全なウェブブラウザです。
             */
            description?: string;
            /**
             * @description スクリーンショットのURL一覧
             * @example [
             *       "https://example.com/screenshot1.png",
             *       "https://example.com/screenshot2.png"
             *     ]
             */
            screenshotUrls?: string[];
            /**
             * @description アプリのカテゴリ
             * @example ブラウザ
             */
            category?: string;
            /**
             * @description 必要最小限のAndroid SDKバージョン
             * @example 21
             */
            minAndroidSdkVersion?: number;
            contentRating?: components["schemas"]["ContentRating"];
            /**
             * Format: date-time
             * @description 最終更新日時（RFC3339形式）
             * @example 2023-01-01T12:00:00Z
             */
            updateTime?: string;
            /**
             * @description 利用可能な国コード（ISO 3166-1 alpha-2）
             * @example [
             *       "US",
             *       "JP"
             *     ]
             */
            availableCountries?: string[];
            /**
             * @description アプリの特徴的な機能
             * @example [
             *       "VPN_APP"
             *     ]
             */
            features?: components["schemas"]["AppFeature"][];
            /** @description このアプリで現在利用可能なバージョン */
            appVersions?: components["schemas"]["AppVersion"][];
            /**
             * @description アプリの詳細説明
             * @example Google Chromeは、Googleが開発した無料のウェブブラウザです。
             */
            fullDescription?: string;
        };
        ApplicationPermission: {
            /**
             * @description 権限を一意に識別する文字列
             * @example android.permission.ACCESS_WIFI_STATE
             */
            permissionId?: string;
            /**
             * @description 権限の名前
             * @example view Wi-Fi connections
             */
            name?: string;
            /**
             * @description 権限を一意に識別する文字列
             * @example Allows the app to view information about Wi-Fi networking, such as whether Wi-Fi is enabled and name of connected Wi-Fi devices.
             */
            description?: string;
        };
        /** @description アプリケーションの管理対象プロパティ */
        ManagedProperty: {
            /**
             * @description アプリがプロパティの識別に使用する一意のキー（例：com.google.android.gm.fieldname）
             * @example com.google.android.gm.fieldname
             */
            key?: string;
            /**
             * @description プロパティのタイプ
             * @example STRING
             * @enum {string}
             */
            type?: "BOOL" | "STRING" | "INTEGER" | "CHOICE" | "MULTISELECT" | "HIDDEN" | "BUNDLE" | "BUNDLE_ARRAY";
            /**
             * @description プロパティの名前（ローカライズ済み）
             * @example Default search provider name
             */
            title?: string;
            /**
             * @description プロパティの詳細な説明（ローカライズ済み）
             * @example If DefaultSearchProviderEnabled is on, then setting DefaultSearchProviderName specifies the default search provider's name. Leaving DefaultSearchProviderName unset means the hostname specified by the search URL is used.
             */
            description?: string;
            /** @description CHOICE または MULTISELECT プロパティの有効なエントリのリスト */
            entries?: components["schemas"]["ManagedPropertyEntry"][];
            /**
             * @description プロパティのデフォルト値（BUNDLE_ARRAY以外）
             * @example default_value
             */
            defaultValue?: string | boolean | number | string[];
            /** @description BUNDLE_ARRAY プロパティの場合のネストされたプロパティリスト（最大2階層） */
            nestedProperties?: components["schemas"]["ManagedProperty"][];
        };
        /** @description 管理対象プロパティのエントリ */
        ManagedPropertyEntry: {
            /**
             * @description エントリの値
             * @example 1
             */
            value?: string;
            /**
             * @description エントリの表示名（ローカライズ済み）
             * @example Allow all sites to set local data
             */
            name?: string;
            /**
             * @description エントリの詳細説明（ローカライズ済み）
             * @example Setting the policy to 1 lets websites run JavaScript. Setting the policy to 2 denies JavaScript. Leaving it unset allows JavaScript, but users can change this setting.
             */
            description?: string;
        };
        /** @description アプリケーショントラックの情報 */
        AppTrackInfo: {
            /**
             * @description 変更不可能な一意のトラックID（Google Play ConsoleのreleaseTrackIdから取得）
             * @example beta
             */
            trackId?: string;
            /**
             * @description trackIdに関連付けられたトラック名（Google Play Consoleで設定可能）
             * @example Beta Track
             */
            trackAlias?: string;
        };
        /**
         * @description アプリケーションの配布チャネル:
         *     - DISTRIBUTION_CHANNEL_UNSPECIFIED: 配布チャネルが指定されていない
         *     - PUBLIC_GOOGLE_HOSTED: Play ストアで公開されており、特定の企業に限定されない
         *     - PRIVATE_GOOGLE_HOSTED: 限定公開アプリ（企業限定）でGoogleがホスト
         *     - PRIVATE_SELF_HOSTED: 限定公開アプリ（企業限定）で自社ホスト
         *
         * @enum {string}
         */
        DistributionChannel: "DISTRIBUTION_CHANNEL_UNSPECIFIED" | "PUBLIC_GOOGLE_HOSTED" | "PRIVATE_GOOGLE_HOSTED" | "PRIVATE_SELF_HOSTED";
        /**
         * @description アプリの価格設定:
         *     - APP_PRICING_UNSPECIFIED: 不明な料金。一般提供されていない承認済みアプリを示す
         *     - FREE: このアプリは無料
         *     - FREE_WITH_IN_APP_PURCHASE: アプリは無料だが、アプリ内購入が可能
         *     - PAID: アプリは有料
         *
         * @enum {string}
         */
        AppPricing: "APP_PRICING_UNSPECIFIED" | "FREE" | "FREE_WITH_IN_APP_PURCHASE" | "PAID";
        /**
         * @description 汎用 IARC 基準に準拠したコンテンツレーティング:
         *     - CONTENT_RATING_UNSPECIFIED: コンテンツレーティングが指定されていない
         *     - THREE_YEARS: 3歳以上のみに適したコンテンツ
         *     - SEVEN_YEARS: 7歳以上のユーザーのみに適しているコンテンツ
         *     - TWELVE_YEARS: 12歳以上のみを対象とするコンテンツ
         *     - SIXTEEN_YEARS: 16歳以上のみを対象とするコンテンツ
         *     - EIGHTEEN_YEARS: 18歳以上のユーザーのみに適しているコンテンツ
         *
         * @enum {string}
         */
        ContentRating: "CONTENT_RATING_UNSPECIFIED" | "THREE_YEARS" | "SEVEN_YEARS" | "TWELVE_YEARS" | "SIXTEEN_YEARS" | "EIGHTEEN_YEARS";
        /**
         * @description アプリに含めることができる機能:
         *     - APP_FEATURE_UNSPECIFIED: 機能が指定されていない
         *     - VPN_APP: アプリがVPNである
         *
         * @enum {string}
         */
        AppFeature: "APP_FEATURE_UNSPECIFIED" | "VPN_APP";
        /** @description アプリの1つのバージョンを表します */
        AppVersion: {
            /**
             * @description Google Play ストアでアプリデベロッパーがバージョンを識別するために使用する文字列
             * @example 131.0.6778.81
             */
            versionString?: string;
            /**
             * @description アプリバージョンの一意の増分識別子
             * @example 677808153
             */
            versionCode?: number;
            /**
             * @description アプリのバージョンが公開されている識別子をトラッキング
             * @example [
             *       "beta",
             *       "stable"
             *     ]
             */
            trackIds?: string[];
            /**
             * @description Trueの場合、このバージョンは製品版トラックであることを示します
             * @example true
             */
            production?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
